aws:
  s3:
    carrierwave:
      bucket: contents-development
      asset_host: <%= "http://#{ENV['DEV_HOST']}:9000/contents-development" %>
      credentials:
        force_path_style: true
        endpoint: <%= ENV['S3_ENDPOINT'] %>
